# runtime: python27
# api_version: 1
# threadsafe: true
# service: match
#
# handlers:
# - url: /.*
#   script: main.app

runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

service: match
